title = "Batmatt"
baseURL = "https://batmatt79.github.io"
languageCode = "en-us"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
resourceDir = "../resources"
omit_header_text = true
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Batmatt79"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages
  [languages.fr]
    title = "Batmatt79"
    weight = 2
    contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "Work in progress."
  background_color_class = "bg-purple"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "Instagram"
url = "https://instagram.com/batmatt79"
