title = "Aphorizm"
baseURL = "https://aphorizm.com"
languageCode = "en-us"
theme = "ananke"
resourceDir = "../resources"
omit_header_text = true
DefaultContentLanguage = "zh"
SectionPagesMenu = "main"
Paginate = 6
googleAnalytics = "G-6B50W0P5K0"
enableRobotsTXT = true

[languages]
  [languages.zh]
    title = "Aphorizm"
    weight = 1
    contentDir = "content/zh"
    # languageDirection = 'rtl' for Right-To-Left languages
  [languages.en]
    title = "Aphorizm"
    weight = 2
    contentDir = "content/en"

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = "images/fav_icon.jpg"
  site_logo = ""
  description = "Self-ownership"
  background_color_class = "bg-prince-purple"
  recent_posts_number = 6

[params.fontAwesome]
  KitURL = "https://kit.fontawesome.com/KitID.js"

[[params.ananke_socials]]
name = "instagram"
url = "https://instagram.com/batmatt79"

[[params.ananke_socials]]
name = "rss"
url = "/index.xml"

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']

[services]
  [services.rss]
    limit = -1